### ISSUE TITLE
open different file types

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#153]
I would really like to have Caliban be able to open different filetypes, including xarrays, tiffs, and pngs. I think being able to open image files could make annotations from scratch much easier. Eg, a file gets opened as a tiff, loaded into a numpy array appropriately, and saved as an npz. Having caliban able to handle different input dimensionalities is probably a prerequisite for this.

**Comment by ngreenwald** [comment]
Hey @MekWarrior and @willgraf, Geneva and I were just discussing what the dimensionality of the data should be that gets passed to caliban from the toolbox. 

Currently, the data is internally stored in the toolbox as [fovs, stacks, crops, slices, rows, cols, channels]. 

- fovs are different fovs that are stacked in the same array
- stacks are z/t stacks of data
- crops are an index into a single crop of the larger fov
- slices are an index into a subset of the z-stack

Caliban currently accepts 4D input: [slices, rows, cols, channels]. If in RGB mode, it assumes that the slice dimension is of length 1, and if not in RGB mode, it attempts to allow cycling through different slices. 

I had structured the toolbox to output 5D data: [crops, slices, rows, cols, channels]. 
For RGB data, the first and second dimension are always 1. For non-RGB data, the second dimension could be either 1 or larger. 

What format do you all think makes the most sense going forward to output? I would like it to be the same size no matter what data type it is, which is why I initially increased the data to 5D. However, we could remove the crops dimension, since it is always going to be 1 for individual files being read into caliban.

**Comment by geneva-miller** [comment]
DCL is currently able to open `.tif` and `.png` images, as well as `.zip` files of raw images and `.npz` and `.trk` files. Since this issue was opened, I think there is also initial support for opening images/files with different numbers and ordering of axes.

Are there other filetypes we know we want to support in addition to these? For example, xarrays, or possibly raw images from a microscope (eg `.nd2` or `.czi`)? Similarly, if there are formats we don't plan on supporting, this issue could be a good place to maintain a record of those decisions and how we arrived at them.
