### ISSUE TITLE
add pytest to repo

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#184]
We should be linting the code more thoroughly as we go. @willgraf anything to note specifically for this?

**Comment by willgraf** [comment]
We can use the `pytest-pep8` plugin to easily lint files using the command `pytest --pep8`.

This should likely be integrated into the Travis CI builds.

**Comment by willgraf** [comment]
This is somewhat resolved by #189 

However, the PR only addresses the Browser tests, and the Desktop build should have its own tests as well (this can be achieved by adding a new workflow to the `.github/workflows` directory. We can also then add another badge to the readme so that status of each build can be seen from github itself.

**Comment by willgraf** [comment]
With #235 the browser application is the only application in the project, and it is tested with GitHub Actions.
