### ISSUE TITLE
Fail to predict according to last frame

### ISSUE THREAD

**Issue by Jeff-Gui** [vanvalenlab/deepcell-label#224]
**Describe the bug**
After labeling all objects in the first frame, the program fails to label the second frame based on prediction.

**To Reproduce**
1. Make .npz file with ['X'] = raw data, ['y'] = mask, cell object labeled with 1
2. Run caliban.py
3. Label all objects on the first frame
4. Enter -> to the second frame, enter S and then P
5. All object in the second frame are still labeled by 1

**Expected behavior**
Objects in the second frame labeled according to labels on the first frame.

**Screenshots**
Labeled first frame
![frame0](https://user-images.githubusercontent.com/48266970/105718410-28bc6f80-5f5c-11eb-9011-358b9c9ed8ad.JPG)

Unlabeled second frame after doing prediction operation.
![frame1](https://user-images.githubusercontent.com/48266970/105718435-2fe37d80-5f5c-11eb-9c37-f103b3963894.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python Version 3.7.10

**Additional context**
I'm not sure if I understand expected behavior of "prediction" correctly. In my view, it should output cell label based on spatial correlation to the previous frame.

**Comment by geneva-miller** [comment]
Hi Jeff, if I'm understanding your issue correctly, all of the objects in the second frame were labeled with `1`. For the IOU-based prediction to work correctly, each of these objects needs to have a different label. Since these labels already exist and are separated from each other, you can split them apart with the flood label action (ctrl + click on region to flood with new label, press space to confirm). Once each label has been flooded, the prediction relabeling should work as expected. 

If the labeling step that produces all 1s is part of your pre-processing workflow, I would recommend using `skimage.measure.label` to give each labeled region a different label before saving the annotation. If you created those labels using the brush in DeepCell Label, in the future I would recommend changing the brush value between labels. Another option is to set the brush to one of the label values and label each slice of the cell in the stack before changing the brush value and moving on to the next cell.

**Comment by Jeff-Gui** [comment]
Hi. I solved the problem by relabeling my input mask as you have said. Thank you.
