### ISSUE TITLE
Tracking more behaviors than division in Label

### ISSUE THREAD

**Issue by tddough98** [vanvalenlab/deepcell-label#225]
I'm looking at the changes that @geneva-miller  has made to expand the tracking behaviors we can track on desktop Label to include merges, deaths, overlaps, and divisions. Looking back at our call on January 20 about porting these changes to browser Label, our goals were to:

- port the metadata changes from desktop Label to browser Label backend so .trk files created in desktop Label are compatible with browser Label and vice versa.
- add an "interesting"/"weird" keybind in browser Label to flag unusual behavior to be further labeled by an expert

Looking at the metadata.py file that Geneva shared with me, I've pulled out a few requirements for porting the metadata changes desktop --> browser

- display the new behaviors to the user
- generate empty behavior data for a new project
- load existing behavior data from a lineage file
- validate behavior data when generating, loading, or changing it

With the current implementation on desktop Label, the data we store for each label looks something like:
```
{0: {'label': 0,
'frames': [],
'frame_text': '',
'capped': False,
'cap_type': None,
'parent': None,
'daughters': [],
'frame_div': None,
'death': False,
'death_type': None,
'frame_died': None,
'merged_from': [],
'merges_into': None,
'frame_merged': None,
'overlaps': {
    'debris_partial': [],
    'debris_total': []
    }
}}
```
Each additional behavior we want to track in the future would require more fields to added every label. Tracking phagocytosis would have every label record the label it phagocytoses and the label it is phagocytosed by, even if it never has this behavior. This can duplicate the data, e.g. both the parent and the daughter record that they were involved in the same division. Tracking rare behaviors bloats every label's data while adding little info to the dataset.

I propose we store the label behavior separately, with a dictionary for each label. For example, if label 1 that divides into label 2 and 3 on frame 5 of a 10 frame movie, the label dictionaries & the behavior dictionaries would look like:
```
label_info = {1: {frames: [0-4]}, 2: {frames: [5-9]}, 3: {frames: [5-9]}}
division_info = [{frame: 5, parent: 1, daughters: [2, 3]},]
```
Other behaviors might look like
```
merge_info = [{frame: 5, parents: [1, 2], daughter: 3}]
death_info = [{frame: 5, label: 1}]
overlap_info = [{frames: [5-9], labels: [1, 2]}]
```
We could validate behaviors by adding rules that cross-reference label_info or other behavior dictionaries. A division could check that the parent only exists before the division frame & the children exist only afterward, and we can check that a label does not both divide and die.  

Notably, the interesting flag for annotators would become another behavior dictionary `interesting_info = [{frame: 1, label: 1}, {frame: 1, label: 2}]`. Any other behavior we would want to track in the future would become another dictionary plus rules about the behavior.

**Comment by geneva-miller** [comment]
I'm really intrigued by this idea, especially since these behaviors can be quite rare. In our datasets so far, I would estimate that < 5% of cells die, while < 1% of cells are involved in a merge event. Even if every cell in a movie had an interesting end to its trajectory, the information dictionary for each cell would be bloated with trivial information about other, mutually exclusive behaviors.

Some questions and considerations that have come to mind over the last few days:

- Currently, all of our .trk files have label information stored per label, rather than per behavior. Should we consider using a different file extension for this alternate lineage format? How should we approach working with the old style of .trk files once we iron this out? Where else will we need to update code to read lineage files?

- As mentioned in today's standup, some behaviors are "capping" while others are transient. Transient behaviors, like overlaps, don't necessarily depend on temporal information, and could be annotated in single-frame files. Do we want to generalize behavior annotation to cover static images, and how does that inform .trk (or similar) file specifications?

- How can we keep track of which behaviors have been annotated in different files? Dvc metadata?

- The current method of marking overlaps is not a complete solution--I would like to iterate on overlap annotation before finalizing behavior annotation, but it's unclear what the best solution would be.

- Potential new behavior field: out of focus cells

**Comment by tddough98** [comment]
> * Currently, all of our .trk files have label information stored per label, rather than per behavior. Should we consider using a different file extension for this alternate lineage format? How should we approach working with the old style of .trk files once we iron this out? Where else will we need to update code to read lineage files?

We might consider converting all of our existing .trk files to the potential new format so that we validate our data with any behavior guard rails we implement. All of our existing .trk files only contain divisions, so we would only have to parse this one type of behavior.

I'm wondering what our current dependence on the .trk lineage file format is outside of Label. @willgraf @MekWarrior, how do we currently use .trk files for model training?

> * As mentioned in today's standup, some behaviors are "capping" while others are transient. Transient behaviors, like overlaps, don't necessarily depend on temporal information, and could be annotated in single-frame files. Do we want to generalize behavior annotation to cover static images, and how does that inform .trk (or similar) file specifications?

I'm thinking we might want to type each field in a behavior as spawning, transient, or capping. For example, the parent field in a division would be capping, while the daughters would be spawning. Each label should appear at most once in a spawning field, at most once in a capping field, and can appear any number of times in a transient field. This would cover behaviors like phagocytosis too, where the consumer would be transient and the consumee would be capping.

We could definitely generalize to single frame files, and in fact, images with no frame dimension are currently expanded to a single-frame stack in Label. Maybe this suggests that we should store the behavior file separately from the labels, so we can add behavior to any segmentation.

I think behaviors should have a frames field that is a list of 1+ frames where the behavior occurs. We currently use frame_div for division, and this would become a list of one frames. Longer events like overlapping would have multiple frames.

> * How can we keep track of which behaviors have been annotated in different files? Dvc metadata?

With crowdsourced interesting flag for unusual behavior, we could track whether the crowd has flagged anything and then track when these interesting flags are converted to more specific behaviors. Not sure if DVC metadata is the right place for this, but I'd imagine we'll want a breakdown of what behavior is present in each file in DeepCell Datasets.

I would imagine some of the behaviors could remain unclassified, so maybe we want another "QCed interesting" for behavior that is still unknown. We could even add a behavior and keep the flag, like if we can tell that it's a cell death but still think it's an unusual cell death that we want to look back on.

> * The current method of marking overlaps is not a complete solution--I would like to iterate on overlap annotation before finalizing behavior annotation, but it's unclear what the best solution would be.

Here are some challenges with overlaps that we should think about:

- when a cell overlaps with 2+ cells in the same place (i.e. one pixel has 3+ cells at that position)
- when a cell overlaps with 2+ cells in the same place (i.e. different cells on different sides)
- when one cell is fully contained within another cell
- when the same two cells overlap in different places (i.e. two opposing, U-shaped cells with both tips touching)
- when any of these cases occur during some frames but not others

I think the current desktop implementation is label/behavior level (i.e. these two labels overlap somewhere on this frame), not pixel level (where is the overlap). Pixel-level overlaps will be quite a challenge, but some options could be:

- add a label dimension to the label array so every label can be present at every pixel
- store a separate overlap array where each overlapping region is given a unique value, then map the regions to labels using the overlap behavior objects

Lastly, we could implement a guard rail for overlaps that checks that the labels are adjacent (or within some threshold like 1-2 pixels).


> * Potential new behavior field: out of focus cells

I buy this, perfect use case.

**Comment by tddough98** [comment]
Also, the spawning, transient, capping categories lend themselves well to displaying relevant information about a label. When we hover over a label, we would see how the label beings (if it appears in a spawning behavior), what the label is doing in the current frame (if it appears in a transient behavior), and how the label ends (if it appears in a capping behavior).

**Comment by geneva-miller** [comment]
> > * The current method of marking overlaps is not a complete solution--I would like to iterate on overlap annotation before finalizing behavior annotation, but it's unclear what the best solution would be.
> 
> Here are some challenges with overlaps to think about:
> 
>     * when a cell overlaps with 2+ cells in the same place (i.e. one pixel has 3+ cells at that position)
> 
>     * when a cell overlaps with 2+ cells in the same place (i.e. different cells on different sides)
> 
>     * when one cell is fully contained within another cell
> 
>     * when the same two cells overlap in different places (i.e. two opposing, U-shaped cells with both tips touching)
> 
>     * when any of these cases occur during some frames but not others
> 
> 
> The current desktop implementation is label/behavior level (i.e. these two labels overlap somewhere on this frame), not pixel level (where is the overlap). Pixel-level overlaps will be quite a challenge, but some options could be:
> 
>     * add a label dimension to the label array so every label can be present at every pixel
> 

I've been thinking about this quite a bit, and I think if we want to fully and accurately annotate images, we need pixel-level overlaps. Without any kind of overlap solution, annotations of cells that overlap can't be made accurately: either cell A is fully labeled at the expense of cell B's label, or a border is semi-arbitrarily decided between the two that results in a somewhat inaccurate label for both A and B. Adding an overlap flag keeps track of where these compromises have been made, but doesn't add enough information to accurately describe the shape of each label and region of overlap.

On the other hand, the number of pixels involved in overlaps in any given frame tends to be relatively small, so approaches that change the way we use/store information in the label array may be more trouble than they're worth.

>     * store a separate overlap array where each overlapping region is given a unique value, then map the regions to labels using the overlap behavior objects
> 

I've been leaning towards something more like this, although I don't think we necessarily need to have a dedicated overlap array or 3rd distinct label to mark the region of overlap. Instead, I'd suggest storing overlap information in behavior dictionaries along the lines of:

```
overlap_info = [{frame: 5, labels: [1, 2], coords: [[35, 146], [35, 147], [36, 147]]}, 
                {frame: 6, labels: [1, 2], coords: [[35, 146], [35, 147], [36, 147], [37, 147]]},
                {frame: 6, labels: [3, 'debris'], coords: [[411, 233], [410, 235]]}]
```
Overlap coordinates need not be exclusive to a single label-label pair. A triple overlap of cells A/B/C would be annotated as regions of overlap between A/B, B/C, and C/A; pixels belonging to an A/B/C overlap would not be explicitly stored but could be extracted from the label pair annotations.

Regions of overlap would be added (or removed) with an "overlap brush" similar to the conversion brush, but with an eraser option. Such a brush would modify the list of overlap points for a pair of labels (or label-debris pair) when drawing over a valid label target. Like the conversion brush, only one target would be allowed at a time--for some label shapes, this may require two passes with the overlap brush (drawing with A over B, then with B over A), but I think this would make it easier to accurately label the overlap region. (I also have ideas about how to display these regions, but I'll go into that at some other time.)

With overlap information stored like this, we would not need to modify the way we use and store label arrays. Label arrays would even continue to have semi-arbitrary boundaries between overlapping cells, instead of introducing additional labels to mark regions of overlap (consistent with existing labeled data). When used in conjunction with stored overlap information, the full label mask for each cell could be generated from the points in label array + the overlap coordinates the label is included in. The overlap coordinates could be used flexibly in other ways as well (train a classifier to predict just overlaps? convert overlap regions in the label array to a distinct 3rd label?).

> 
> Lastly, we could implement a guard rail for overlaps that checks that the labels are adjacent (or within some threshold like 1-2 pixels).

Suggested guard rails: 

- overlap brush only draws over one target at a time
- "trim pixels" action expanded to remove non-contiguous pixels from overlap points list, when overlap behavior annotations are present (ie, the cell mask being trimmed is generated from the label array + overlap points, and overlap points and labeled pixels that are not connected to that full cell mask are trimmed; cells that overlap with each other in more than one spot would not necessarily have the overlaps trimmed away because they don't connect with each other)
- probably some visual indicator and/or text display to notify user when overlap region contains non-contiguous pixels
- potentially restrict use of overlap brush to label pairs that have been marked as having an overlap? this may be overkill for desktop DCL use, but could be incorporated in some form into the browser version for crowdsourcing (expert quickly marks overlapping cells, annotators perform the more time-intensive brush work?)

**Comment by willgraf** [comment]
Some great discussion here, I love the idea of generalizing the behaviors and I think you're on the right track.

Regarding overlaps: Do we want to encode the layering of objects? (i.e. "object 1 is on top of object 2")

**Comment by geneva-miller** [comment]
Recording object layering is an interesting idea, but there are many cases where it can't be determined, for example:
![image](https://user-images.githubusercontent.com/45578681/106959931-3f975a80-66f0-11eb-946b-293f81cbf66a.png)

The main case where we can determine object layering is when one of the objects detaches from the imaging surface, which we can infer from a change in focus. In some cases, we have access to 3D context (eg, several phase images recorded at different z offsets that inform a single fluorescent channel), which can help support object layering judgments, especially in difficult cases.

For 3D annotations, we may want to record overlaps in regions where the resolution between slices is not particularly high, but in those cases I would expect object layering judgments to be redundant when taken in context with adjacent labeled slices.

Overall, my inclination would be to store information about objects that are out of focus and use that in conjunction with overlap annotations if we wanted to reconstruct object layering. This doesn't quite cover the case where both objects are out of focus (one visibly more out of focus than the other), but I think that consideration has more to do with how out-of-focus annotations should be recorded.

**Comment by geneva-miller** [comment]
> We can generalize to single frame files, and in fact, images with no frame dimension are currently expanded to a single-frame stack in Label. Does this suggest we should store behavior files separately segmentation arrays, so we could add behavior to any segmentation?

I would like to support this, especially for annotation of overlap regions.

Another reason I'm interested in supporting generalized behavior annotations is that I think this approach could be a good way to finally support different semantic classes. Grouping labels into different classes (for example, to annotate heterogeneous cell populations) has been on our radar for a while, but is somewhat tricky to implement using arrays and pixel-level changes.

**Comment by geneva-miller** [comment]
>>  How can we keep track of which behaviors have been annotated in different files? Dvc metadata?
>
> With crowdsourced "interesting" flag for unusual behavior, we could track whether the crowd has flagged anything and then track when these flags are converted to more specific behaviors. Not sure if DVC metadata is the right place for this, but I'd imagine we'll want a breakdown of what behavior is present in each file in DeepCell Datasets. 

The way I'm thinking about it, there's two aspects to this. For each file, does the behavior field exist? And if it does, does it contain anything of interest? For example, if we wanted to work with merge events, files that didn't include the merge behavior field (eg, earlier versions of .trk files) would not be helpful. Files that support merge annotations but didn't actually have any merge events would also be unhelpful. I agree that DeepCell Datasets should be able to quickly access that information in some way.

> I'd imagine some of the flagged cells could remain unclassified, so would we want another "QCed interesting" for behavior that is still unknown? We could even add a behavior and keep the flag, like if we can tell that it's a cell death but think it's an unusual cell death that we want to look back on.

I like the idea of tracking the conversion of "interesting" flags into specific behaviors. I think it may also be useful to keep the "interesting" flag around (or use a similar flag) to make a note of unusual behaviors; maybe having a field that can contain a note about the behavior? Unusual behaviors I've seen lately and would flag are things like "unhealthy division" (cell looks like it's about to die, manages to divide, daughter cells die shortly after), "failed division" (cell looks like it's about to undergo a normal/healthy division, but dies partway through instead), and "abnormal shape" (division appeared to be going normally, one of the daughters behaved very weirdly for a few frames, but ended up seeming to recover). It's hard to say ahead of time what types of unusual behavior will come up, though!

**Comment by MekWarrior** [comment]
From the discussion here and on slack it sounds like the focus should be on label dictionaries & behavior/type/class dictionaries, e.g.: 
`label_info = {1: {frames: [0-4]}, 2: {frames: [5-9]}, 3: {frames: [5-9]}}`
`division_info = [{frame: 5, parent: 1, daughters: [2, 3]},]`

We should make it robust enough to handle both "dynamic behaviors" (like divisions, merges, death, etc) and "static types" or "classes" (semantic segmentation like cell type or which organelle belongs to which cell). I believe this could be addressed as part of our solution for where to store the data and what the appropriate file format is (e.g. .trk or zip). My suggestion would be to "broaden" the lineage file to accommodate these new dictionaries. JSON would allow for as many (or as few) entries to exist as necessary to describe the image/movie. This file could be stored together with the image files as a zip or tarball. DVC can be used to manage changes to the entire archive or the individual files. 

It may be worth considering the use of multiple channels in the annotated array. This could allow for easy storage of semantic information discussed above and make inheritance straightforward. I'd prefer to focus on these issues before overlaps.

**Comment by tddough98** [comment]
Closing this issue as it's based in an outdated version of DeepCell Label. Tracking more behaviors is still of interest, but will look different will the 0.4 release of DeepCell Label. See #340 for an outline of how to add new types of labels.
