### ISSUE TITLE
misc issues introduced with MVC rework

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#234]
**Describe the bug**
Typos in infopane
`Press the W W to use the Watershed tool.`
```
feature tells us which labeled features we are viewing
Features may be [FILL IN] 
```

Cycling through foreground values also changes background values (undesired behavior).

**To Reproduce**
1. Select a label (eg set 1 as the foreground and background as the background)
2. Press `[` to cycle backwards through labels (or `]` to cycle forwards
3. When labels are cycled around to the first or last label in the file, the background label changes

**Expected behavior**
When cycling between foreground labels, the background value should remain unchanged, even when changing between first/last label.

**Additional context**
There may also be other unintended or undesired behaviors that I haven't found yet via user testing

**Comment by tddough98** [comment]
cycling the foreground or the background moves through cycles through every label, so when cycling past the other selected label, the two will swap so that the foreground and background are not the same. I added this behavior after Geneva asked that the foreground and background not ever be the same label, even while cycling.

Should cycling allow the foreground and background to be the same? Or should cycling skip over the other selected label? Or should we keep the current behavior

**Comment by willgraf** [comment]
`W W` typo is resolved in #235

**Comment by tddough98** [comment]
`Features may be [FILL IN]` is also resolved in #235

**Comment by geneva-miller** [comment]
Ctrl + B to toggle RGB mode is also the shortcut to show bookmarks in a sidebar on Firefox, this default behavior should be disabled

**Comment by geneva-miller** [comment]
Typos in Canvas tab of infopane: 

"DeepCell Label can adjust how to dispaly labels and images" (change "dispaly" -> "display")

"The right-side canvas shows an images and labels" (change "an images" -> "an image")

**Comment by geneva-miller** [comment]
Entering and leaving brush mode of interaction does not update brush preview until mouse moves. Brush circle should appear immediately when the brush is turned on, and disappear immediately when the brush is turned off
