### ISSUE TITLE
Phase viewing issues

### ISSUE THREAD

**Issue by epao111** [vanvalenlab/deepcell-label#247]
**Is your feature request related to a problem? Please describe.**
When viewing phase images individually (not in overlay mode) the image normalization plus the color map make the images very difficult to see. The combination seems to remove a lot of contrast. In overlay mode, the image changes to grey scale so the issue is resolved.

**Describe the solution you'd like**
Allow users to change the viewing mode of the raw images.

**Comment by geneva-miller** [comment]
Could you clarify what you mean by "viewing mode"? It also sounds like there's two visualization issues here--colormaps and contrast. Phase images are often difficult to view without contrast adjustment, even with a grayscale colormap.

**Comment by geneva-miller** [comment]
Closing because both aspects of this issue (unhelpful colormaps and contrast adjustment) have been addressed:
* channels can be displayed in grayscale in multichannel viewing mode
* channels can be displayed one at a time in grayscale via single-channel mode
* both viewing modes allow brightness/contrast adjustment
