### ISSUE TITLE
Frame list for a cell lineage does not match the y data

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-label#278]
A data error appeared in one of the files we tracked with DCL. It's hard to know if the error was actually introduced by DCL, but we wanted to document it here anyway in case there is a fix for it.

The frame list for a cell lineage ended up missing frames from the end of the movie where the cell was clearly present in the movie. `deepcell_tracking.utils.is_valid_lineage` raised `/usr/local/lib/python3.6/dist-packages/deepcell_tracking/utils.py:507: UserWarning: Cell 14 has invalid frames`

https://github.com/vanvalenlab/data-registry/blob/1b58ea6d7515862c6e5301757fc9b17d32887430/data/labels/dynamic/2d/RAW264.7/journal_pcbi_1005177/RAW264_s2_p2_1c.trk.dvc

The project id associated with this file is recorded in the [job log](https://github.com/vanvalenlab/data-registry/blob/master/data/jobs/RAW2647-tracking-2-log-2021-09-08-200737.yaml).

**Comment by tddough98** [comment]
This was fixed by 56d71e38ef3781398e2455af0c52e4ec05a1fe04 on the tracking-ui branch. The specific issue was on line 747 where replace_with_parent updated the frame for just one frame, instead of all the frames edited.

The fix is currently deployed for Anolytics, and I'll close the issue when tracking is merged into main.
