### ISSUE TITLE
Parent cell not present in lineage

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-label#279]
This is another issue that may have been introduced by DCL during tracking annotation. `deepcell_tracking.utils.is_valid_lineage` raises the error `Parent 103 is not present in the lineage`. Inspection of the data shows that label 103 is not present in `y`, but seems to be expected somewhere in the lineage data.

https://github.com/vanvalenlab/data-registry/blob/1b58ea6d7515862c6e5301757fc9b17d32887430/data/labels/dynamic/2d/RAW264.7/journal_pcbi_1005177/RAW264_s2_p0_1c.trk.dvc

Log file: https://github.com/vanvalenlab/data-registry/blob/75e3869d47d1c0e5695897d8b5622198b42ce313/data/jobs/RAW2647-tracking-1-log-2021-08-31-191604.yaml

**Comment by tddough98** [comment]
This was fixed with ddca25a2e5b8d5b6fec0e5e20d32796e386d2eb4 on the tracking-ui branch. Instead of updating the parent that was removing, the replace action was resetting the parent that we we're keeping which was both causing cells to have one sided divisions (this was the issue that motivated the fix) and causing parents that were not in the segmentation to be in the lineage (this issue here).

The fix is currently deployed for Anolytics and I'll close this issue when tracking is merged into the main branch.
