### ISSUE TITLE
Deleted cell reappears with label 0

### ISSUE THREAD

**Issue by elaubsch** [vanvalenlab/deepcell-label#367]
**Describe the bug**
Deleted cell reappears with label 0 after a second cell is deleted

**To Reproduce**

1. Ran Caliban prediction on deepcell.org and viewed results
2. Changed to CELLS tab and selected ALL mode
3. Selected a cell and deleted it
4. Selected another cell and deleted it
5. Old cell label reappeared
6. Hovered over the old cell with SELECT tool, saw label value is set to 0

**Expected behavior**
A deleted cell should not reappear.

**Screenshots**
![Screen Recording 2022-08-19 at 11 50 42 AM](https://user-images.githubusercontent.com/43769564/185688275-4053b983-44d0-48ab-9d07-dfe752260ba3.gif)

**Comment by ykevu** [comment]
It seems like this is primarily a visual bug related to #365, so the fix to that issue should address this as well. With that change, cells do still reappear but making any further edits should clean up the improperly deleted cells, but I'll still look into why they reappear at all.

**Comment by ykevu** [comment]
I was able to figure out what was causing this bug. The gpu library used to render the canvas seems to have a bug (?) where out-of-bounds indexing of an array gives unexpected values instead of undefined, so when deleting last cell(s) on a given frame, the kernel still thought the labels were there. By adding an if statement to check if the value the kernel is rendering is within the expected range of values, this bug should be fixed.
