### ISSUE TITLE
zoom in and out

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#41]
It would be useful to add ability to zoom in and out while annotating

**Comment by geneva-miller** [comment]
This is on the horizon for the desktop version! Some considerations:

- preferably, you could pan across a zoomed image whether or not you are in pixel-editing mode

  - click&drag in pixel-editing mode draws with the brush (or creates a thresholding box), and I don't want to change this functionality to correspond to a modified click&drag

  - holding down space + click&drag is a way to pan across images in some other applications, and I think this could work nicely in Caliban, but the key to confirm actions would need to be reassigned. I'm thinking "enter" would be a nice choice. I'm open to alternative keybinding stategies

- there needs to be a way to tell when you are at the edge of the image

  - I think this could pretty easily be accomplished by changing how the lines around the window are drawn (eg, draw lines only on the edges where we are at the edge of the image)

  - almost as important, I think users need to know when the selected label(s) are also present outside of the FOV. This could also be accomplished with lines--if labels are out of FOV, red (instead of white) lines on those edges indicate where the labels are?

  - I'm open to suggestions here

- how to zoom

  - probably ctrl+scroll, I'm reluctant to also assign keybinds to this. I think there'll be a keybind to reset zoom to 100%

  - possible levels of zoom: I don't want to zoom out (zoom < 100%) for the time being and will probably set a maximum zoom, currently thinking 600%

Let me know if anything else comes to mind that I might need to take into account.

**Comment by ngreenwald** [comment]
That's great! Thoughts below.

- I think holding space + dragging is a great solution, and will be familiar to many. Swapping with enter seems quite reasonable to me

- I think having the lines only show up when at the edges makes sense. In terms of labels outside of the current FOV, this doesn't happen in 2D images, since we don't have runaway labels, so I don't have much advice on the best way to handle this for tracking/3D annotation.

- ctrl sounds good. I think either a zoom reset key, or a text infographic next to frame/label indicator that shows the current zoom level would be nice. 

- For a future improvement, definitely doesn't have to be included in V1 release, something similar to FIJI with a little inset showing where your current zoom box is in relation to the whole image.

**Comment by geneva-miller** [comment]
Still needs to get merged together with RGB mode for desktop, and browser could do with zoom as well, but #103 brings us a lot closer.

**Comment by MekWarrior** [comment]
#130 sets the stage for adding to zoom to the browser version.

**Comment by geneva-miller** [comment]
Browser needs zoom (and likely #51 as a precursor) to facilitate accurate, precise annotations.

**Comment by willgraf** [comment]
@geneva-miller Can this issue be closed with #149?

**Comment by willgraf** [comment]
Both browser and desktop support zoom, so I will close this issue. Please re-open it if I am closing in error.
