### ISSUE TITLE
display channel names

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#45]
Currently channels are displayed based on their index; being able to provide a set of text labels associated with each channel and display that would be helpful for annotating to know what channel is being displayed

**Comment by geneva-miller** [comment]
We may hardcode channel names (or general channel descriptions--would it be okay to just say "nuclei" instead of the specific nuclear marker?) into the RGB class we discussed. We could also investigate having Caliban open xarrays in the future and handle the channel names that way.

**Comment by ngreenwald** [comment]
I think for a first pass for the multichannel data class, hardcoding them is totally fine. I think that reading from xarrays is the nicer long-term solution.

**Comment by geneva-miller** [comment]
The way channels are interacted with has changed since this issue was opened, but we are still interested in being able to display specific channel names.

Example of the current channel interface (two channels displayed): 
![image](https://user-images.githubusercontent.com/45578681/166290145-580da6f9-749f-4a25-8657-6dcac5a2cb31.png)

The cell-types offshoot of DCL supports displaying user-defined names instead of "channel 0", etc., via a JSON file included by the user when initializing a project. That implementation is fragile and may need restructuring before it can be applied to a more general range of DCL projects.

Some other thoughts/considerations:

- I think passing in channel names via xarray is still an intriguing option 
- users should be able to name or rename channels from the DCL interface
  - perhaps not part of the MVP implementation of this feature
  - useful for starting from image files/image files + predictions/file formats that don't include this metadata
  - user-defined metadata should persist/be part of the data download/export
