### ISSUE TITLE
save checkpoint or undo feature for browser users

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#60]
In desktop Caliban, users can save frequently so that if they make a mistake, they can go back to a previous save instead of starting annotation over from scratch. We don't have a way to allow this for browser users, since the file is saved only when it is submitted. Pixel-editing is a little more robust to mistakes since annotators can erase or re-draw annotations, but bulk label editing mistakes can take more work to undo.

Ideally, we would have an "undo" command that undoes the most recent command. (I'm not sure how we would implement that, or if we'd be able to extend it to being able to undo/redo multiple commands.) What may be easier to implement is a save/load checkpoint feature. One checkpoint could be stored at a time that annotators could use to reload their file from. Since this relies on annotators remembering to checkpoint their file at appropriate intervals, this is less ideal than "undo" but could still work as a compromise until undo is implemented.

**Comment by geneva-miller** [comment]
Maybe each time an action is performed, the state of the object before the action could be saved in a different field? If the user chooses the "undo" action, this previous state would be loaded. This would only let users undo up to one action, but it would add "undo" capability. Alternatively, we could do something similar to allow annotators to have one saved checkpoint at a time.

**Comment by ngreenwald** [comment]
Maybe storing 1 (or more) snapshots of the previous state that could be reverted to?

I think a natural way of setting of this snapshot might be once edits begin on a new cell label. For example, once edits (pixel or otherwise) are made to cell 5, a snapshot is created. This snapshot is preserved until edits are made to a different cell, for example cell 15, at which point the state before cell 15 was edited becomes the last snapshot. The user could then revert to this previous snapshot if they make a mistake.

**Comment by ngreenwald** [comment]
I think just saving the 'y' image would be fairly lightweight. What about having a queue of say length 5 or 10. Every time 'y' is modified, it gets added to the queue and the nth entry is dequeued off the back? Then undoing is just traversing through the list of 10 images?

**Comment by geneva-miller** [comment]
#212 added "undo" functionality and #214 also lets users return to in-progress projects via project ID.
