### ISSUE TITLE
reduce lag for browser caliban

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/deepcell-label#68]
- try timing functions to identify slowest parts
- look into reducing how often object needs to be pickled/unpickled
- do connections need to be closed each time, or can we maintain a persistent connection to the db?

**Comment by geneva-miller** [comment]
Addressed by #75. May be other ways we can reduce lag so I'm leaving this open for now.

**Comment by willgraf** [comment]
I think using `async` functions should also help the usability here.  Won't make any of the existing functions faster, but could make the page feel a bit snappier by not locking up whenever something is executing.

**Comment by ngreenwald** [comment]
Yeah, any ideas you have for this Will would be great. Currently there's about a 1/4-1/2 second lag for actions. Once you get used to it you start doing the next action before the previous one has finished, but would be nice to smooth out sometime in the future.

**Comment by geneva-miller** [comment]
Maybe? But then I think there's a lot that would still need to be disabled until the updated frame is returned. I think using `async` functions could actually lead to a more confusing experience. Eg, annotator tries to watershed a label to split it, but nothing appears to happen. So they switch to pixel-editing mode and start to use the conversion brush, but partway through the labels update--what happens to the conversion brush? That type of thing is what I'm concerned about with `async`

**Comment by willgraf** [comment]
> try timing functions to identify slowest parts
I've submitted #157 which logs the time it takes for most backend functions.

> do connections need to be closed each time, or can we maintain a persistent connection to the db?
Since #144 we have been allowing flask to manage the database connections, so we no longer have to worry about the

**Comment by ngreenwald** [comment]
Currently there's about a 1 second lag on most actions in browser, which is slightly annoying but manageable. However, for larger images, the lag time increases significantly. This makes it prohibitively slow to work with images larger than say 250x250 pixels. 

Given that we are standardizing our image size to be 512x512, it would be great if we could speed things up enough so that images of that size can be edited in a reasonable time. This would allow us to load full images, rather than crops, once our annotators are skilled enough to use zoom.

**Comment by MekWarrior** [comment]
Speed improvements are ongoing but this issue is stale. Closing in response to backend reformatting and sunsetting of js version in favor of React.
