### ISSUE TITLE
Check that all labels are sequential

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-label#73]
In some cmap handling we check for max(track label), we should either verify that all labels are sequential or switch to len(unique labels)

**Comment by MekWarrior** [comment]
Non-sequential labels (e.g. 1,2,4,6,7...) can cause error in different pipelines. Model predictions that users will interact with are guaranteed to be sequential, therefore, it is assumed that the input to Caliban will likely have this constraint. We should introduce either an option to relabel sequentially or to do this automatically when the file is saved.

**Comment by geneva-miller** [comment]
Desktop npz mode does have relabeling options, which we did not port over to the browser version as we deemed it unnecessary for crowd work. We could port that into the browser version if needed. The functionality currently missing is relabeling trk files so that lineage information is updated appropriately as well.

I think `max` is appropriate for cmaps so that images can be rendered whether or not they are sequential, but for downstream applications we should at least have a relabel option, and perhaps also include it upon saving. My main question is if there are any reasons we should *not* relabel upon saving for either npzs or trks.

**Comment by geneva-miller** [comment]
As our pipelines and DCL have changed over time, I think sequential relabeling is best handled outside of the DCL interface. Between the improvements to colormaps/label visualization and label highlighting that goes to the next existing label, nonsequential labels don't necessarily hinder annotation and review of files in DCL.

However, there are some cases where I've found that sequential labeling can help to methodically review files (especially those with many cells or longer movies), so I'd like to leave this issue open for now.

**Comment by tddough98** [comment]
This would be only planned outside of this repo, so I'm closing this issue here.
