### ISSUE TITLE
different modes with limited features available

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#92]
As we begin to accumulate more features, and potentially have annotators who have seen different versions of the instructions before, I think it could be useful to add in the option to specify either a whitelist of commands that will work, or a blacklist of commands that won't work, to restrict the number of buttons that have functionality at any one time

**Comment by geneva-miller** [comment]
This is definitely something we want for the browser version, as a way to make sure annotators are using exactly the tools we want them to use for the particular job. Is this something you anticipate also needing for desktop?

**Comment by ngreenwald** [comment]
Exactly! I think this makes the most sense for browser, I don't see a need
in the near term for desktop

**Comment by geneva-miller** [comment]
The way I would like to implement this is by adding url options to flask routes. This would probably be along the lines of:
`@app.route("/load/<filename>", methods=["POST"])`
goes to
`@app.route("/load/<filename>/options/<config>", methods=["POST"])`
where config can specify certain flags that get passed to initialize the javascript in a particular way. Some that come to mind are whether to use rgb display or not, or which editing features to allow.

I would like to maintain backwards compatibility such that not including any options defaults to using single channel caliban with all features enabled.

This would require some additions to the caliban pipeline (so that users could specify these flags before fig8 job creation). It would also require some changes to the javascript files to apply the flags appropriately.

I think this is one option we have to get RGB browser version up and running. (An alternative would be using .xr files exclusively for RGB mode at first, then later adding in these url options/flags, but I think starting with flags and adding .xr files later is an easier way forward.)

**Comment by ngreenwald** [comment]
Got it, happy to adapt whichever way you think is easiest for the toolbox!

**Comment by geneva-miller** [comment]
I think limited modes may still be useful as we continue to expand the repertoire of tools within DCL. (For example, it may be useful to disable segmentation tools for jobs focused on correcting tracking lineage assignments.) However, I don't think the original "rgb mode" is useful anymore, and I'm not sure which modes may have been introduced in the meantime. 

@tddough98 are there any limited modes currently implemented for the main branch?

**Comment by tddough98** [comment]
I'm actively exploring this with the different visualizer variants right now. The mesmer viewer in #243 from a year ago was the first case of a limited functionality mode. We now have

- a mesmer viewer (needs to be updated) (viewer.deepcell.org)
- a spots viewer (spots.deepcell.org)
- a caliban/tracking viewer (in development, will have a demo at our standup tomorrow, will be hosted at tracks.deepcell.org)
- the full labeling app (label.deepcell.org and anolytics.deepcell.org)

The full labeling app supports both editing labels for segmentation and tracking. When `track=true` is added to the URL, we show a tabbed menu for segmentation and tracking controls and switch between the two of them. 

I'm working on how to reconcile the different visualizers and allow them all to coexist without building and hosting separate sites. Definitely open to suggestions on how to combine these modes. @msschwartz21 suggested looking at napari, and I think @MekWarrior mentioned cell pose as an example too
