### ISSUE TITLE
Standardize labels display across pixel and label editing mode

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-label#93]
Currently, whether annotations are displayed is tracked and controlled separately for label vs pixel editing mode. 

On the control side, the keybindings are different:

- In pixel mode, "L" toggles between whether or not the annotations are displayed. 
- In labels mode, "L" no longer toggles between whether or not the annotations are displayed, it toggles between displaying contours or the labels. Instead, "Z" is used to toggle between displaying or not displaying the annotations.

Additionally, whether or not contours are currently being displayed is tracked separately for labels and pixel mode. For example, if "L" was selected in pixel editing mode, and then "e" is pressed to switch to label editing mode, the annotations disappear, because annotations haven't yet been turned on (via "z") in label editing mode.  

Another potential source of confusion is that "L" only toggles between contours and labels in label editing mode if "z" has already been pressed to display annotations. If annotations have not been turned on, "L" does not switch between the two views, and does nothing. 

Suggestions:

- Pick either "L" or "Z" to be the key in both editing modes that turns displaying annotations on or off. I'll use "Z" here for illustrative purposes
- Track whether annotations have been enabled across both modes, so that switching between modes does not result in annotations appearing/disappearing, even if "Z" has not been selected in both modes
- Even if annotations are not currently enabled (via "Z"), allow the user to switch between contour and label visualization modes with "L"
- Allow the user to switch between contour and label visualization, using "L", whether they are in pixel or label mode

**Comment by geneva-miller** [comment]
Thanks for articulating this, your feedback really helps!

I agree with the first two suggestions but am not sure what you mean by the third suggestion. Also, I don't intend to add label-only visualization to pixel-editing mode, so I don't think the fourth suggestion applies.

So, what the update is likely to be is that Z will be used to toggle between viewing the raw-only image and a display that includes annotations. This will apply to both label- and pixel-editing mode, so that switching between those modes maintains a similar display. L will be used to toggle the particular label display method if you are currently viewing the annotations in label-editing mode.

How does that sound?

**Comment by ngreenwald** [comment]
Got it!

Yeah, I see that the wording on my third suggestion is confusing. If you're in label editing mode, and currently are looking at the raw data (ie, Z is disabled), pressing L does nothing. I think pressing L should always switch to viewing the labels. Does that make sense?

I think it would be useful to be able to see the labels, even in pixel editing mode. The reason is that the contour-overlay sometimes makes it difficult to determine what the underlying labels actually look like when there are multiple labels next to one another, especially if you've conversion-brushed pixels from one to another. Is there a reason that this is difficult to implement, or you just don't think it would be that useful?

**Comment by geneva-miller** [comment]
Okay, I see what you're saying with L. I was envisioning that as a bidirectional toggle (switching between contours and labels) but it sounds like you'd like it to be more unidirectional (pressing L turns on solid-label viewing whether or not you were viewing the contours). Would you still want to use L to switch out of solid-label viewing? I'm reluctant to change the behavior too much away from a bidirectional toggle, since many keybinds in Caliban work that way and I'd like the behavior to be generally consistent.

Viewing the solid-color labels on a black background in pixel-editing mode should not be too difficult to implement. My main hesitation here is that I see the point of pixel-editing mode as getting the labels to more precisely match the raw images, and editing the pixels without being able to see the raw images seems counter-intuitive. I'd prefer to try other ways of improving pixel-editing mode before adding a solid-label viewing mode. One thing that has worked nicely on a different branch for pixel-editing mode is changing the thickness of the contour lines to be thinner, which might improve the display for you. Also, are you using highlighting in pixel-editing mode, and is that helping?

**Comment by ngreenwald** [comment]
These two are actually related, maybe it would be worth it to explain the use case. 

Generally, for the super dense cells, I often find it helpful to toggle the labels on and off, while looking at the raw images, so assess any remaining errors. This currently works great for the contour outline in pixel editing mode. Toggling the contours on and off lets the user look at the color overlay and determine if anything is still incorrect. 

I would like to have the same functionality in label editing mode. Toggling the solid-color labels on and off, while looking at the raw images to see if there are any remaining errors. Because this is the primary use case I see for turning the labels on/off in label editing mode, having the intermediate step of turning all labels off in between, before specifically switching to color-label view, doesn't seem useful to me. 

For the same reason, having the option to toggle the color-labels on and off, while in pixel editing mode, would be useful for assessing stray pixels, borders that didn't exactly get smoothed in the right place, etc. 

Does that make sense?

**Comment by geneva-miller** [comment]
I'm not sure I follow. I'm going to make an initial change based on the first two suggestions, and then let's iterate on that.

**Comment by ngreenwald** [comment]
I went back based on our discussion and played around with the new changes you pushed. I think for now it makes the most sense to keep the color-label view bi-directional, as you suggested.

**Comment by geneva-miller** [comment]
Okay, so I think the remaining part of this issue is whether or not to somehow include the solid-color labels in pixel-editing mode. Do you have thoughts on how you'd like that to be implemented/if you still think we should add that?

**Comment by ngreenwald** [comment]
Yes, I think it can be useful, especially for more advanced annotators, to be able to look at labels. 

Ideally 'L' would work in pixel editing mode the same way it does in label editing mode, and would alternate between the two views. Then all of the actions would work the same way they currently do, just with the different view.

**Comment by tddough98** [comment]
Closed by #248 as it removes separate label editing and pixel editing modes and uses the same display controls throughout the app
